
# This file is generated by Makefile.

# comando para rodar o build_runner
# make mobx
mobx:
	@fvm flutter pub run build_runner watch --delete-conflicting-outputs

clean:
	@fvm flutter clean && fvm flutter pub get




