name: movies
description: "Pro Filmes"


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  mobx: ^2.3.3+2
  dio: ^5.7.0
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.0.10+1
  flutter_local_storage: ^0.0.1
  flutter_secure_storage: ^9.2.2
  grock: ^0.5.7
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.1





flutter:

  assets:
   - assets/images/
   - assets/icons/

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
